"""Base MongoDB Adapter"""
from abc import ABC
from datetime import timezone
from typing import Dict, Any, Optional
from dataclasses import fields as get_fields
from bson import ObjectId
from bson.codec_options import CodecOptions
from motor.core import AgnosticDatabase, AgnosticCollection
from motor.motor_asyncio import AsyncIOMotorClientSession


class BaseMongoAdapter(ABC):
    """
    Base class for MongoDB collection adapters

    Supports optional session for transaction management.
    When session is provided, all collection operations participate in transaction.
    """

    collection_name: str = None

    def __init__(self, db: AgnosticDatabase, session: Optional[AsyncIOMotorClientSession] = None):
        """
        Initialize adapter

        Args:
            db: MongoDB database instance
            session: Optional session for transactions (None for non-transactional ops)
        """
        self._db = db
        self._session = session

        # Initialize collection for static adapters
        if self.collection_name:
            self._col = self._get_collection(self.collection_name)

    @property
    def db(self) -> AgnosticDatabase:
        """Get database instance"""
        return self._db

    @property
    def col(self) -> AgnosticCollection:
        """Get collection instance"""
        if not hasattr(self, '_col'):
            raise AttributeError(
                "Dynamic adapters should use _get_collection() instead of col property"
            )
        return self._col

    @property
    def session(self) -> Optional[AsyncIOMotorClientSession]:
        """
        Get current session (if in transaction context)

        Returns:
            AsyncIOMotorClientSession if in transaction, None otherwise
        """
        return self._session

    def _get_collection(self, collection_name: str) -> AgnosticCollection:
        """Get collection with timezone-aware codec options"""
        return self._db[collection_name].with_options(
            codec_options=CodecOptions(
                tz_aware=True,
                tzinfo=timezone.utc
            )
        )

    @staticmethod
    def proj(*fields: str, include_id: bool = True) -> Dict[str, int]:
        """Build MongoDB projection from fields"""
        projection = {field: 1 for field in fields}
        if include_id and '_id' not in fields:
            projection['_id'] = 1
        return projection

    @staticmethod
    def entity_projection(entity_class) -> Dict[str, int]:
        """Generate MongoDB projection from entity dataclass"""
        field_names = [f.name for f in get_fields(entity_class) if f.name != 'id']
        return BaseMongoAdapter.proj(*field_names)

    @staticmethod
    def prepare_for_insert(doc: Dict[str, Any]) -> Dict[str, Any]:
        """Convert entity dict to MongoDB document (id -> _id)"""
        doc = {**doc}  # Copy to protect original
        if 'id' in doc:
            if doc['id'] is not None:
                try:
                    doc['_id'] = ObjectId(doc['id'])
                except Exception as e:
                    raise ValueError(
                        f"Invalid 'id' field value: '{doc['id']}'. "
                        "Do not send 'id' field when creating new documents. "
                        "The id will be auto-generated by MongoDB."
                    ) from e
            doc.pop('id')
        return doc

    @staticmethod
    def prepare_for_read(doc: Dict[str, Any]) -> Dict[str, Any]:
        """
        Convert MongoDB document to JSON-serializable dict.

        Recursively converts:
        - _id field to id (as string)
        - All ObjectId instances to strings

        Args:
            doc: MongoDB document

        Returns:
            JSON-serializable dictionary
        """
        if doc is None:
            return None

        doc = {**doc}  # Copy to protect original

        # Convert _id -> id (string)
        if '_id' in doc:
            if isinstance(doc['_id'], ObjectId):
                doc['id'] = str(doc['_id'])
            else:
                doc['id'] = doc['_id']
            doc.pop('_id')

        # Recursively convert all ObjectId fields
        for key, value in list(doc.items()):
            if isinstance(value, ObjectId):
                doc[key] = str(value)
            elif isinstance(value, dict):
                doc[key] = BaseMongoAdapter.prepare_for_read(value)
            elif isinstance(value, list):
                prepared_list = []
                for item in value:
                    if isinstance(item, dict):
                        prepared_list.append(BaseMongoAdapter.prepare_for_read(item))
                    elif isinstance(item, ObjectId):
                        prepared_list.append(str(item))
                    else:
                        prepared_list.append(item)
                doc[key] = prepared_list

        return doc
